### ISSUE TITLE
Failed to resolve lib

### ISSUE THREAD

**Issue by linean** [erz05/JoyStick#1]
I'm getting: Failed to resolve: com.github.erz05:JoyStick:1.0.3@aar. I have added jcenter repo.

**Comment by erz05** [comment]
Ill look into it :)
Ill update the library

**Comment by erz05** [comment]
@linean sorry I didn't have it in jcenter I'm in the process of having it linked there

but it is in maven
you can use this
```groovy

repositories {
    maven {
        url  "http://dl.bintray.com/erz05/maven" 
    }
}

I updated the README
dependencies {
    compile 'com.github.erz05:JoyStick:1.0.3'
}
```

I updated the README!
